server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: course_route
          uri: http://course-edge-service:5051/course/
          predicates:
            - Path=/course/**
        - id: user_route
          uri: http://user-edge-service:4041/user/
          predicates:
            - Path=/user/**
