spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_course
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

dubbo:
  application:
    name: course-dubbo-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    host: 127.0.0.1
    port: 5050
  scan:
    base-packages: cn.sun.course.service

thrift:
  user:
    ip: 127.0.0.1
    port: 4040
