version: "3.4"

networks:
  default:
    driver: overlay
    name: micro-overlay
    external: false
      # name: micro-overlay


services:

  message-service:
    build: ./message-thrift-service/
    image: sun/message-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"
    environment: 
      PYTHONUNBUFFERED: 1

  user-service:
    build: ./user-thrift-service/
    image: sun/user-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    command:
      - "--mysql.address=172.24.137.158"

  user-edge-service:
    build: ./user-edge-service/
    image: sun/user-edge-service:latest
    deploy:
      endpoint_mode: vip
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8082:4041"
    depends_on: 
      - user-service
      - message-service
    command: 
      - "--redis.address=172.24.137.158"

  course-service:
    build: ./course-dubbo-service/
    image: sun/course-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    depends_on:
      - user-service
    command:
      - "--mysql.address=172.24.137.158"
      - "--zookeeper.address=172.24.137.158"

  course-edge-service:
    build: ./course-edge-service/
    image: sun/course-edge-service:latest
    deploy:
      endpoint_mode: vip
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8081:5051"
    depends_on: 
      - course-service
      - user-edge-service
    command: 
      - "--zookeeper.address=172.24.137.158"

  api-gateway:
    build: ./api-gateway-zuul/
    image: sun/api-gateway:latest
    deploy:
      endpoint_mode: vip
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8080:8080"
    depends_on: 
      - user-edge-service
      - course-edge-service
