version: "3.8"

networks:
  default:
    driver: overlay
    external: false
      # name: micro-overlay


services:

  message-service:
    image: localhost/micro-service/message-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"
    environment:
      PYTHONUNBUFFERED: 1

  user-service:
    image: localhost/micro-service/user-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "256M"
    command:
      - "--mysql.address=192.168.142.1"

  user-edge-service:
    image: localhost/micro-service/user-edge-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "256M"
    depends_on:
      - user-service
      - message-service
    command:
      - "--redis.address=192.168.142.1"

  course-service:
    image: localhost/micro-service/course-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "256M"
    depends_on:
      - user-service
    command:
      - "--mysql.address=192.168.142.1"
      - "--zookeeper.address=192.168.142.1"

  course-edge-service:
    image: localhost/micro-service/course-edge-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "256M"
      placement:
        constraints: [ node.role == manager ]
    healthcheck:
        test: ["CMD", "wget", "-S", "http://localhost:5051/"]
        interval: 60s
        timeout: 10s
        retries: 3
    depends_on:
      - course-service
      - user-edge-service
    command:
      - "--zookeeper.address=192.168.142.1"

  api-gateway:
    image: localhost/micro-service/api-gateway:latest
    deploy:
      endpoint_mode: vip
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "256M"
    ports:
      - "8080:8080"
    depends_on:
      - user-edge-service
      - course-edge-service
