version: '3.8'

networks:
  default:
    driver: bridge
    external: false

services:
  message-service:
    build: ./message-thrift-service/
    image: sun/message-service:latest
    container_name: message-service
    restart: on-failure
    environment:
      PYTHONUNBUFFERED: 1

  user-service:
    build: ./user-thrift-service/
    image: sun/user-service:latest
    container_name: user-service
    restart: on-failure
    command:
      - "--mysql.address=172.29.49.188"

  user-edge-service:
    build: ./user-edge-service/
    image: sun/user-edge-service:latest
    container_name: user-edge-service
    restart: on-failure
    depends_on:
      - user-service
      - message-service
    command:
      - "--redis.address=172.29.49.188"

  course-service:
    build: ./course-dubbo-service/
    image: sun/course-service:latest
    container_name: course-service
    restart: on-failure
    depends_on:
      - user-service
    command:
      - "--mysql.address=172.29.49.188"
      - "--zookeeper.address=172.29.49.188"

  course-edge-service:
    build: ./course-edge-service/
    image: sun/course-edge-service:latest
    container_name: course-edge-service
    restart: on-failure
    depends_on:
      - course-service
      - user-edge-service
    command:
      - "--zookeeper.address=172.29.49.188"

  api-gateway:
    build: ./api-gateway-zuul/
    image: sun/api-gateway:latest
    container_name: api-gateway
    restart: on-failure
    depends_on:
      - user-edge-service
      - course-edge-service
    ports:
      - "8080:8080"
