service:
    name: user-thrift-service
    port: 4040

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/db_user
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always
