server:
    name: course-edge-service
    port: 5051

dubbo:
    application:
        name: course-edge-service
    registry:
        address: zookeeper://${zookeeper.address}:2181
    scan:
        base-packages: cn.sun.course.edge
