server:
    name: course-edge-service
    port: 5051

dubbo:
    application:
        name: course-edge-service
    registry:
        address: zookeeper://127.0.0.1:2181
    scan:
        base-packages: cn.sun.course.edge
