server:
  name: user-edge-service
  port: 4041

spring:
  redis:
    host: ${redis.address}
    port: 6379
    password: redis
    timeout: 3000

thrift:
  user:
    ip: user-service
    port: 4040
  message:
    ip: message-service
    port: 6060
